### PR TITLE
Fixed access to a member property right after a function call

### LINKED ISSUE #335: Unable to access to a member property after a function call
**Describe the bug**
Unable to access to a member property after a function call

**To Reproduce**
Here is a query:
```
LET items = [{name: "foo"}]
RETURN FIRST(items).name
```

**Expected behavior**
Must return "foo" string.

**Actual behavior**
Returns an entire object.

### PR DESCRIPTION
**Pull request by ziflex**
Closes #335

### CODE REVIEW

File: pkg/compiler/visitor.go [hunk 1]
```diff
@@ -736,15 +736,39 @@ func (v *visitor) doVisitForExpressionStatement(ctx *fql.ForExpressionStatementC
...
+	var source core.Expression
+	var children []antlr.Tree
 
-	_, err := scope.GetVariable(varName)
+	identifier := ctx.Identifier()
 
-	if err != nil {
-		return nil, err
+	if identifier != nil {
+		varName := ctx.Identifier().GetText()
```
Comment (3timeslazy) [inline pkg/compiler/visitor.go]: Why not just `identifier.GetText()`?

Comment (ziflex) [reply pkg/compiler/visitor.go]: 🤷‍♂️for clarity, I guess 😄

Comment (ziflex) [reply pkg/compiler/visitor.go]: Because I use the variable to do an existence check
